language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-android-support
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

script:
  - echo "twitterConsumerKey=$TWITTER_CONSUMER_KEY" >> app/fabric.properties
  - echo "twitterConsumerSecret=$TWITTER_CONSUMER_SECRET" >> app/fabric.properties
  - echo "apiSecret=$API_SECRET" >> app/fabric.properties
  - echo "apiKey=$API_KEY" >> app/fabric.properties
  - ./gradlew clean build

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/